### ISSUE TITLE
View Stockroom

### ISSUE THREAD

**Issue by halsowadi** [COSC481W-2022Fall/capstone-project-sour-patch-kids#2]
Expected Workload: S or M

User Story: _As a user, I’d like to be able to view all my assets within a stockroom so that I can view their statuses and determine the necessary actions to update/replace them._

Tasks:
- [ ] Properly display stockrooms within organizations.
- [ ] Give the ability for users to click on a stockroom and display it's contents (for Sprint 1, they will always be empty.)

Acceptance Criteria: 

- Users must be able to view the empty stockrooms that have been created.
- Users must only be able to see stockrooms that are within organizations they are a member of.

**Comment by sjiang1** [comment]
How the users can see what assets may or may not be available to them if the stockroom will always be empty?
