### ISSUE TITLE
Bugfix: Cannot fetch error on some API calls

### ISSUE THREAD

**Issue by smick00** [COSC481W-2022Fall/capstone-project-sour-patch-kids#22]
User Story: As a user of stuff stash, I expect the website to properly function when interacting with the server.

Bug Report:
1.) Environment: Browser
2.) How to Reproduce: Refresh on any page other than the welcome page within the deployed project.
3.) Expected: Refresh shouldn't throw an error.
4.) Actual: Refreshing any pages with a URL extension causes an error.
5.) Screenshot: [https://i.imgur.com/VtysinW.png](url)

Tasks:

- [x]  Fix the "cannot fetch" error on API calls.

Acceptance Criteria: 

- [x] "Cannot fetch" error no longer occurs on API calls.

**Comment by sjiang1** [comment]
Please include a bug report here:

1. environment (os, browser, version, etc.)
2. steps to reproduce the bug
3. expected outcome
4. actual outcome
5. visual proof (screenshot)

**Comment by smick00** [comment]
I've included the bug report as requested. Is it safe to assume that this is the format you'd like us to use for all bugs going forward?

**Comment by sjiang1** [comment]
Yes.

Environment: browser --> needs to specify what kind of browser: chrome? firefox? ie? etc. Also get a version number of your browser with the OS you are using, like `chrome 106.0.5249.119 on Windows 11` If the OS/browser version doesn't matter, you can skip it.

The screenshot link doesn't work. You can copy the image and paste the image here. GitHub will generate a link for you.

**Comment by smick00** [comment]
Hey, we ended up fixing this by switching to Digital Ocean hosting. As such there weren't any changes to the code. What would you like us to do with this PR?

**Comment by smick00** [comment]
This bugfix has been resolved without any changes to the code. Closing.
