### ISSUE TITLE
Include List of Stockrooms View In Dashboard

### ISSUE THREAD

**Issue by mpochowi** [COSC481W-2022Fall/capstone-project-sour-patch-kids#24]
User Story: As a user of stuff stash, once I login into my account, I'd like to view the stockrooms within an organization I am a member of.

Tasks:

- [x] When viewing an organization, display a list of stockrooms assigned to that org.

Acceptance Criteria:

- [x] Once logged in and on the dashboard, the user should be able to view the stockrooms of an organization they're a part of.

**Comment by sjiang1** [comment]
In the sprint review, there should be some stockrooms in the database to demo this feature.
