### ISSUE TITLE
Users need to be able to join multiple organizations

### ISSUE THREAD

**Issue by mpochowi** [COSC481W-2022Fall/capstone-project-sour-patch-kids#29]
User story: As a user of Stuff Stash, I should be able to join as many organizations as I would like. 

Tasks: 

- [x] Update user model to include an array of Org access codes instead of a single element. 
- [x] Include method/function to make sure there are no duplicates

Acceptance Criteria:

User will be associated with multiple organizations.

**Comment by sjiang1** [comment]
Any changes in the front end so that users can join multiple organizations?

Acceptance criteria:

- Users will be able to join multiple organizations.

**Comment by smick00** [comment]
Not within this issue. All of the frontend tweaks for joining organizations will be handled within #20 , which will ultimately just mean putting the button that links to the existing page in a proper spot there. Our current front end framework should work perfectly fine for that purpose.
