### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by halsowadi** [COSC481W-2022Fall/capstone-project-sour-patch-kids#3]
Expected Workload: S

User Story: _As a user of Stuff Stash, I’d like to be able to reliably, securely, and easily log into my account so I can utilize the services offered._

Tasks:
- [x] Create an API that checks user inputs with currently stored inputs and logs them in if an EXACT match is found (once decrypted).
- [x] Create a frontend webpage for users to log in from.
- [x] Link the frontend webpage to and from other webpages for easy navigations.

Acceptance Criteria: 

- [x]  When user enters their username and password correctly and press login they will be taken to their account homepage.

- [x]  When user enters incorrect username and/or password they will get a pop up indicating that they entered the wrong credentials.

- [x]  If either username or passwords fields are left blank, the user will get a warning informing them the required information is missing when a login attempt is made.
- [x] Once user clicks login, they will have the opportunity to logout from the home page

**Comment by sjiang1** [comment]
Add one acceptance criterion:
The user will stay logged in unless they click log out or their session timed out.

You can modify this one to suit your need.
