### ISSUE TITLE
Bugfix: Deployed app crashes on refresh

### ISSUE THREAD

**Issue by mpochowi** [COSC481W-2022Fall/capstone-project-sour-patch-kids#31]
User Story: As a user of Stuff Stash, I’d like to be able to refresh my pages without crashing. 

Tasks: 
- [x] Fix bug that causes deployed app to crash on refresh.

Acceptance Criteria: 
- [x] Deployed app no longer crashes on refresh.

**Comment by CrazyJokes-dev** [comment]
Fixed this bug accidentally in issue #30
