### ISSUE TITLE
Adding Users to Organization

### ISSUE THREAD

**Issue by halsowadi** [COSC481W-2022Fall/capstone-project-sour-patch-kids#5]
Expected Workload: S

User Story: _As an organization Administrator on Stuff Stash, I'd like the ability to add users to my organization so we can take advantage of the services provided._

Tasks:
- [x] Create an API that allows users to enter an Organization ID, and then check if it is valid. If it is, add the user to that organization indefinitely.
- [x] Add a button that allows users to input an Organization ID.
- [x] Update the database to reflect new users.
- [x] Handle sessions to allow users to see ONLY the organizations that they are a part of.

Acceptance Criteria:
1. Organizations should have a built in _access code_ that is unique and can be used by employees to enter an organization.
2. Users will have a button to press that will prompt them to enter an access code. If they successfully submit a valid access code, they will be added to the associated organization and will be allowed to indefinitely view users and stockrooms within the organization.
3. If a user enters an invalid access code, or does not enter anything, they will be given an error and asked to enter again.

**Comment by sjiang1** [comment]
Is this Organization ID the _access code_ in Acceptance Criterion 1?

**Comment by smick00** [comment]
> Is this Organization ID the _access code_ in Acceptance Criterion 1?

Yes - I've gone ahead and updated the criteria to show that more clearly.

**Comment by smick00** [comment]
Closed with pull request #17 .
